"""Curated open-source repositories dataset for bootstrapping vector search and offline resilience."""

from backend.schemas.ingest import RepoIngestItem

CURATED_REPOSITORIES: list[RepoIngestItem] = [
    RepoIngestItem(
        repo_id=89229960,
        full_name="tiangolo/fastapi",
        html_url="https://github.com/tiangolo/fastapi",
        description="FastAPI framework, high performance, easy to learn, fast to code, ready for production.",
        language="Python",
        stars=78500,
        forks=6700,
        open_issues=420,
        license="MIT",
        topics=["fastapi", "asyncio", "python", "rest-api", "web", "pydantic"],
        pushed_at="2026-09-20T10:00:00Z",
        readme_summary="FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.8+ based on standard Python type hints.",
    ),
    RepoIngestItem(
        repo_id=141888062,
        full_name="encode/starlette",
        html_url="https://github.com/encode/starlette",
        description="The little ASGI framework that shines. High performance asyncio web services.",
        language="Python",
        stars=10200,
        forks=1100,
        open_issues=85,
        license="BSD-3-Clause",
        topics=["asgi", "asyncio", "python", "web-framework"],
        pushed_at="2026-09-18T14:00:00Z",
        readme_summary="Starlette is a lightweight ASGI framework/toolkit, ideal for building async web services in Python.",
    ),
    RepoIngestItem(
        repo_id=10360341,
        full_name="pallets/flask",
        html_url="https://github.com/pallets/flask",
        description="The Python micro framework for building web applications.",
        language="Python",
        stars=68000,
        forks=16000,
        open_issues=12,
        license="BSD-3-Clause",
        topics=["flask", "wsgi", "python", "microframework"],
        pushed_at="2026-09-15T09:00:00Z",
        readme_summary="Flask is a lightweight WSGI web application framework designed to make getting started quick and easy.",
    ),
    RepoIngestItem(
        repo_id=78241477,
        full_name="pydantic/pydantic",
        html_url="https://github.com/pydantic/pydantic",
        description="Data validation using Python type hints, powered by Rust core.",
        language="Python",
        stars=23500,
        forks=2200,
        open_issues=310,
        license="MIT",
        topics=["pydantic", "validation", "typing", "rust", "dataclass"],
        pushed_at="2026-09-21T18:00:00Z",
        readme_summary="Data validation and settings management using Python type hinting with high performance Rust core.",
    ),
    RepoIngestItem(
        repo_id=8579222,
        full_name="pandas-dev/pandas",
        html_url="https://github.com/pandas-dev/pandas",
        description="Flexible and powerful data analysis / manipulation library for Python.",
        language="Python",
        stars=44000,
        forks=17000,
        open_issues=3400,
        license="BSD-3-Clause",
        topics=["pandas", "data-analysis", "dataframe", "python", "datascience"],
        pushed_at="2026-09-24T12:00:00Z",
        readme_summary="pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with structured data both easy and intuitive.",
    ),
    RepoIngestItem(
        repo_id=595781362,
        full_name="shadcn-ui/ui",
        html_url="https://github.com/shadcn-ui/ui",
        description="Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.",
        language="TypeScript",
        stars=74200,
        forks=6200,
        open_issues=210,
        license="MIT",
        topics=["react", "tailwind", "radix-ui", "components", "design-system"],
        pushed_at="2026-09-22T08:00:00Z",
        readme_summary="A collection of re-usable React components styled with Tailwind CSS and Radix UI primitives.",
    ),
    RepoIngestItem(
        repo_id=70107786,
        full_name="vercel/next.js",
        html_url="https://github.com/vercel/next.js",
        description="The React Framework for the Web.",
        language="TypeScript",
        stars=126000,
        forks=27300,
        open_issues=1600,
        license="MIT",
        topics=["nextjs", "react", "ssr", "typescript", "fullstack"],
        pushed_at="2026-09-25T16:00:00Z",
        readme_summary="Next.js is the flexible React framework that gives you building blocks to create fast, full-stack web applications.",
    ),
    RepoIngestItem(
        repo_id=9339907,
        full_name="microsoft/TypeScript",
        html_url="https://github.com/microsoft/TypeScript",
        description="TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
        language="TypeScript",
        stars=99000,
        forks=12500,
        open_issues=5200,
        license="Apache-2.0",
        topics=["typescript", "compiler", "language", "javascript"],
        pushed_at="2026-09-25T20:00:00Z",
        readme_summary="TypeScript syntax gives you type annotations, compiler-enforced contracts, and productive developer tooling.",
    ),
    RepoIngestItem(
        repo_id=10270250,
        full_name="facebook/react",
        html_url="https://github.com/facebook/react",
        description="The library for web and native user interfaces.",
        language="JavaScript",
        stars=228000,
        forks=46200,
        open_issues=850,
        license="MIT",
        topics=["react", "javascript", "ui", "frontend", "declarative"],
        pushed_at="2026-09-24T19:00:00Z",
        readme_summary="React is a JavaScript library for building user interfaces with component-based architecture and virtual DOM.",
    ),
    RepoIngestItem(
        repo_id=10639145,
        full_name="tailwindlabs/tailwindcss",
        html_url="https://github.com/tailwindlabs/tailwindcss",
        description="A utility-first CSS framework for rapid UI development.",
        language="JavaScript",
        stars=82000,
        forks=4100,
        open_issues=15,
        license="MIT",
        topics=["css", "tailwindcss", "utility-first", "responsive"],
        pushed_at="2026-09-23T11:00:00Z",
        readme_summary="A utility-first CSS framework packed with classes that can be composed to build any design directly in your markup.",
    ),
    RepoIngestItem(
        repo_id=160284197,
        full_name="tokio-rs/tokio",
        html_url="https://github.com/tokio-rs/tokio",
        description="A runtime for writing reliable, asynchronous, and slim network applications with the Rust programming language.",
        language="Rust",
        stars=27500,
        forks=2500,
        open_issues=160,
        license="MIT",
        topics=["rust", "async", "networking", "futures", "runtime"],
        pushed_at="2026-09-20T11:00:00Z",
        readme_summary="Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications.",
    ),
    RepoIngestItem(
        repo_id=718388836,
        full_name="astral-sh/uv",
        html_url="https://github.com/astral-sh/uv",
        description="An extremely fast Python package and project manager, written in Rust.",
        language="Rust",
        stars=42500,
        forks=1400,
        open_issues=310,
        license="MIT",
        topics=["python", "rust", "packaging", "pip", "virtualenv"],
        pushed_at="2026-09-25T14:00:00Z",
        readme_summary="An extremely fast Python package manager and resolver, 10-100x faster than pip, written in Rust.",
    ),
    RepoIngestItem(
        repo_id=233488820,
        full_name="qdrant/qdrant",
        html_url="https://github.com/qdrant/qdrant",
        description="Qdrant - High-performance, massive-scale Vector Database and Vector Search Engine for the next generation of AI.",
        language="Rust",
        stars=21000,
        forks=1400,
        open_issues=210,
        license="Apache-2.0",
        topics=["vector-search", "database", "rust", "neural-search", "embeddings"],
        pushed_at="2026-09-21T06:00:00Z",
        readme_summary="Qdrant is a vector similarity search engine and vector database providing production-ready API for vector search with payload.",
    ),
    RepoIngestItem(
        repo_id=208222956,
        full_name="tauri-apps/tauri",
        html_url="https://github.com/tauri-apps/tauri",
        description="Build smaller, faster, and more secure desktop and mobile applications with a web frontend.",
        language="Rust",
        stars=85000,
        forks=2500,
        open_issues=280,
        license="Apache-2.0",
        topics=["desktop", "gui", "rust", "security", "cross-platform"],
        pushed_at="2026-09-23T15:00:00Z",
        readme_summary="Tauri is an app construction toolkit that lets you build desktop and mobile apps with your favorite frontend framework while leveraging a secure Rust backend.",
    ),
    RepoIngestItem(
        repo_id=23096959,
        full_name="golang/go",
        html_url="https://github.com/golang/go",
        description="The Go programming language compiler, tools, and runtime.",
        language="Go",
        stars=122000,
        forks=17500,
        open_issues=8900,
        license="BSD-3-Clause",
        topics=["go", "compiler", "language", "runtime"],
        pushed_at="2026-09-25T21:00:00Z",
        readme_summary="Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.",
    ),
    RepoIngestItem(
        repo_id=21404169,
        full_name="gin-gonic/gin",
        html_url="https://github.com/gin-gonic/gin",
        description="Gin is a HTTP web framework written in Go (Golang). It features a Martini-like API with much better performance.",
        language="Go",
        stars=78000,
        forks=8000,
        open_issues=98,
        license="MIT",
        topics=["gin", "framework", "rest-api", "go", "http"],
        pushed_at="2026-09-19T05:00:00Z",
        readme_summary="Gin is a web framework written in Go with high performance router, middleware support, and crash-free crash handling.",
    ),
    RepoIngestItem(
        repo_id=20580901,
        full_name="kubernetes/kubernetes",
        html_url="https://github.com/kubernetes/kubernetes",
        description="Production-Grade Container Scheduling and Management.",
        language="Go",
        stars=110000,
        forks=39000,
        open_issues=2400,
        license="Apache-2.0",
        topics=["kubernetes", "containers", "cloud-native", "orchestration"],
        pushed_at="2026-09-25T18:00:00Z",
        readme_summary="Kubernetes is an open source system for managing containerized applications across multiple hosts.",
    ),
    RepoIngestItem(
        repo_id=420489953,
        full_name="oven-sh/bun",
        html_url="https://github.com/oven-sh/bun",
        description="Incredibly fast JavaScript runtime, bundler, test runner, and package manager – all in one.",
        language="Zig",
        stars=76000,
        forks=2800,
        open_issues=2100,
        license="MIT",
        topics=["zig", "javascript", "runtime", "bundler", "package-manager"],
        pushed_at="2026-09-25T22:00:00Z",
        readme_summary="Bun is an all-in-one JavaScript runtime & toolkit designed for speed, complete with a bundler, test runner, and package manager.",
    ),
    RepoIngestItem(
        repo_id=1234797,
        full_name="elixir-lang/elixir",
        html_url="https://github.com/elixir-lang/elixir",
        description="Elixir is a dynamic, functional language for building scalable and maintainable applications.",
        language="Elixir",
        stars=24500,
        forks=3300,
        open_issues=35,
        license="Apache-2.0",
        topics=["elixir", "functional", "erlang", "otp", "concurrency"],
        pushed_at="2026-09-22T17:00:00Z",
        readme_summary="Elixir leverages the Erlang VM, known for running low-latency, distributed, and fault-tolerant systems.",
    ),
    RepoIngestItem(
        repo_id=2325298,
        full_name="torvalds/linux",
        html_url="https://github.com/torvalds/linux",
        description="Linux kernel source tree.",
        language="C",
        stars=180000,
        forks=53000,
        open_issues=390,
        license="GPL-2.0",
        topics=["linux", "kernel", "operating-system", "c"],
        pushed_at="2026-09-25T23:00:00Z",
        readme_summary="The Linux kernel source code repository maintained by Linus Torvalds.",
    ),
]
