"""Schemas package exports."""

from backend.schemas.auth import (
    AuthResponse,
    ForgotPasswordRequest,
    LoginRequest,
    MessageResponse,
    ResetPasswordRequest,
    SignupRequest,
    TokenResponse,
    VerifySignupOTPRequest,
)
from backend.schemas.ingest import (
    BatchRepoIngestRequest,
    BatchRepoIngestResponse,
    RepoIngestItem,
)
from backend.schemas.search import (
    RepoItem,
    RepoScoreBreakdown,
    RepoSearchFilter,
    RepoSearchRequest,
    RepoSearchResponse,
)
from backend.schemas.learning import (
    SkillLevel,
    MaterialType,
    CitedMaterial,
    LearningModule,
    LearningMaterialRequest,
    LearningMaterialResponse,
    StructuredAgentOutput,
)
from backend.schemas.chatbot import (
    UserSkillProfile,
    CodeSnippet,
    ChatbotRequest,
    StructuredChatbotOutput,
    ChatbotResponse,
)
from backend.schemas.github import (
    ProjectResponse,
    ContributorResponse,
    SyncResponse,
    ContributorSyncResponse,
)
from backend.schemas.events import (
    EventCreate,
    EventResponse,
)
from backend.schemas.users import (
    UserCreate,
    UserLogin,
    UserLoginResponse,
    UserResponse,
    UserUpdate,
)
from backend.schemas.otp import (
    OTPRequest,
    OTPResponse,
    OTPVerify,
)
from backend.schemas.roadmaps import (
    RoadmapCreate,
    RoadmapListResponse,
    RoadmapResponse,
    RoadmapUpdate,
    StepCreate,
    StepResponse,
    StepUpdate,
    ProgressCreate,
    ProgressResponse,
    ProgressUpdate,
    RoadmapProgressSummary,
)

__all__ = [
    "AuthResponse",
    "BatchRepoIngestRequest",
    "BatchRepoIngestResponse",
    "ForgotPasswordRequest",
    "LoginRequest",
    "MessageResponse",
    "RepoIngestItem",
    "RepoItem",
    "RepoScoreBreakdown",
    "RepoSearchFilter",
    "RepoSearchRequest",
    "RepoSearchResponse",
    "ResetPasswordRequest",
    "SignupRequest",
    "TokenResponse",
    "VerifySignupOTPRequest",
    "SkillLevel",
    "MaterialType",
    "CitedMaterial",
    "LearningModule",
    "LearningMaterialRequest",
    "LearningMaterialResponse",
    "StructuredAgentOutput",
    "UserSkillProfile",
    "CodeSnippet",
    "ChatbotRequest",
    "StructuredChatbotOutput",
    "ChatbotResponse",
    "ProjectResponse",
    "ContributorResponse",
    "SyncResponse",
    "ContributorSyncResponse",
    "EventCreate",
    "EventResponse",
    "UserCreate",
    "UserLogin",
    "UserLoginResponse",
    "UserResponse",
    "UserUpdate",
    "OTPRequest",
    "OTPResponse",
    "OTPVerify",
    "RoadmapCreate",
    "RoadmapListResponse",
    "RoadmapResponse",
    "RoadmapUpdate",
    "StepCreate",
    "StepResponse",
    "StepUpdate",
    "ProgressCreate",
    "ProgressResponse",
    "ProgressUpdate",
    "RoadmapProgressSummary",
]
